apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
type: Opaque
data:
  postgresql-password: {{ b64enc .Values.postgresPassword }}
  postgresql-postgres-password: {{ b64enc .Values.postgresRootPassword }}
  postgresql-replication-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: app-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
type: Opaque
data:
  postgresql-password: {{ b64enc .Values.postgresPassword }}